name: Notify Merge Repo on Java File Change

on:
  push:
    paths:
      - 'src/app/src/main/java/com/sampleapp/utils/AutomationIdLocatorsAndroid.java' # update for iOS repo
      - 'src/Sample_App/Sample_App/Presentation/AutomationIdLocatorsIos.java'        # update for Android repo

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger merge repo workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.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 }}" \
            https://github.com/pradeepmiller/auto-test-app/dispatches \
            -d '{"event_type":"merge_java_locators"}'
